#ifndef SUPPORTEDBUTTONBOARDS_H
#define SUPPORTEDBUTTONBOARDS_H


#if BUTTONBOARD_VERSION==BUTTONBOARD_IS_ZWS_6PIN_9BUTTON_RGB_LED
inline void buttonboard_print_name(){ SerialDebugln(F("ZWS buttonboard : 6PIN 9 BUTTON RGB LED"));}
#define BUTTON_A_ANALOG BUTTONBOARD_BUTTON_A_ANALOG
#define BUTTON_B_ANALOG BUTTONBOARD_BUTTON_B_ANALOG
#define BUTTON_C_ANALOG BUTTONBOARD_BUTTON_C_ANALOG
#define LED_RGB BUTTONBOARD_LED_G

#elif BUTTONBOARD_VERSION==BUTTONBOARD_IS_ZWS_6PIN_9BUTTON_RG_LED
inline void buttonboard_print_name(){ SerialDebugln(F("ZWS buttonboard : 6PIN 9 BUTTON 2 LED"));}
#define BUTTON_A_ANALOG BUTTONBOARD_BUTTON_A_ANALOG
#define BUTTON_B_ANALOG BUTTONBOARD_BUTTON_B_ANALOG
#define BUTTON_C_ANALOG BUTTONBOARD_BUTTON_C_ANALOG
#define LED_R BUTTONBOARD_LED_R
#define LED_G BUTTONBOARD_LED_G

#else
#error "Unsupported BUTTONBOARD_VERSION"
#endif

#endif
